### ISSUE TITLE
prompt weight usage

### ISSUE THREAD

**Issue by rockerBOO** [lowfuel/progrock-stable#45]
I have been playing with the new prompt weights a little bit but trying to figure out how I should be using it.

- Are weights based on 1 or 0? so is `ghost:1 == ghost`?
- Combining multiple words to weight together possible? I have been trying like `'blade runner':2` (with the quotes) but not sure if its working or not. 
- Is it a good idea to keep the weights closer or to really grasp bigger integers? I noticed a normalizer which should scope them in, but is this also scoping in the other default weights?

Thank you.

**Comment by KnoBuddy** [comment]
I don't believe there is a difference between

Ghost, ghost:1, and ghost:100

At least by itself. 

I found using weight from -5 to 15 to give enough room for me to work with without using decimals. 

Yes you can use multiple words for each weight.

Ex
```
A beautiful picture of:10 
A castle:15 
In the Scottish Highlands:7 
Trending on ArtStation:10 
By Beeple and Bob Ross:6 
Blur, depth of field, film grain, out of focus:-2 
```

**Comment by rockerBOO** [comment]
Thank you @KnoBuddy . I am now more confused :). 

The weights in the last part, they apply the weight to the whole prefix?

For instance, I have this as a prompt.

```
cute:10 ghost ghostly boo cyberpunk:4 'blade runner':4 '_artist_':10 _environment_ _lighting_ _colors_ _adjective_
```
Is this not accurate? I basically wanted to weight each word separately, but maybe that's not right. Are you using new lines in a prompt there?

**Comment by rockerBOO** [comment]
Ok I read up a little on the pull request you made, and the origin source code and it has this

```
# grabs all text up to the first occurrence of ':' as sub-prompt
# takes the value following ':' as weight
# if ':' has no value defined, defaults to 1.0
# repeats until no text remaining
```

```
cute:10 ghost ghostly boo:1 cyberpunk blade runner:4 _artist_:10 _environment_  _lighting_ _colors_ _adjective_
```

So I think this would be an accurate representation of what I want.

**Comment by KnoBuddy** [comment]
If you want 

Cute to be weight 10

And ghost boo etc to be weight 1

then yes. That is correct.

Also the last section with no weight will be automatically weighted 1 as well.

**Comment by rockerBOO** [comment]
yes, this works. Thank you @KnoBuddy ! Maybe we can infer this into the README for others.

**Comment by KnoBuddy** [comment]
If you're still confused about how the weights work you can check out the GUI I made specifically for the weights being added to PRS over in https://GitHub.com/KnoBuddy/visualdiffusion

**Comment by JPPhoto** [comment]
Has anyone had success with PRS and negative prompt weights? I'm getting some strange results even when the sum of all weights > 0.
